# Generated by Django 4.2.7 on 2023-11-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashing", "0002_monthlyreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyreport",
            name="total_expense",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="monthlyreport",
            name="total_income",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
